name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install system deps
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential libdrm-dev libdrm-amdgpu1 pkg-config

            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

            - name: Build
              run: |
                  cargo build --release
              shell: bash

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: release-${{ matrix.os }}
                  path: |
                      target/release/slim-osc*
                      target/release/slim-osc*.exe
